<?php
module_load_include('php', 'acb', 'src/Form/acb_layout_form');
module_load_include('php', 'acb', 'src/Form/acb_settings_form');
module_load_include('php', 'acb', 'src/Helper/AcbLoadBlock');
/**
 * @file acb.module 
 */

use Drupal\acb\Model\AcbModelClass;
use Drupal\acb\Helper\AcbHelper;

/**
 * Implements hook_help().
 */
function acb_help($path, $arg) {
  switch ($path) {
    case 'admin/help/#acb':
      return
        '<p>'. t('Acb it\'s an alternative layout sistem to Drupal block core, context, panelizer, and panels.') .'</p>'.
        '<p>'. t('The aproach in Acb module is thay you can select by url where do you want to have your blocks') .'</p>';
      break;
  }
}


/**
 * Implements hook_permission().
 */
function acb_permission() {
  return [
    'administer acb layout' => [
      'title' => t('Administer acb layout'),
      'description' => t('Perfom administration tasks for acb module.'),
    ],
  ];
}
/**
 * Implements hook_menu().
 */
function acb_menu() {
  $items = [];
  
  $items['node/%node/block_layout'] = [
    'title' => 'Block layout',
    'page callback' => 'acb_node_configure_block',
    'page arguments' => array('node',1),
    'access arguments' => array('administer acb layout'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'acb_page.inc'
  ];

  $items['admin/structure/acb'] = [
		'title' => t('List of elements'),
		'description' => t('Acb module options'),
		'page callback' => 'acb_list_elements',
		'access arguments' => ['administer acb layout'],
    'type' => MENU_NORMAL_ITEM,
    'file' => 'acb.admin.inc',
  ];
	$items['admin/structure/acb/list'] = [
		'title' => t('Block Layout'),
		'page callback' => 'acb_list_elements',
		'access arguments' => ['administer acb layout'],
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'file' => 'acb.admin.inc',
	];
  
  $items['admin/structure/acb/settings'] = [
    'title' => t('Configure ACB settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['acb_settings_form'],
    'access arguments' => ['administer acb layout'],
    'type' => MENU_LOCAL_TASK,
    'file' => 'src/Form/acb_settings_form.php',
  ];
  
  $items['admin/structure/acb/add'] = [
    'title' => t('Alternative block layout'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['acb_layout_form'],
    'access arguments' => ['administer acb layout'],
    'type' => MENU_LOCAL_TASK,
    'file' => 'src/Form/acb_layout_form.php'
  ];
  
  $items['admin/structure/acb/%/delete'] = [
    'title' => t('Delete this option'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['acb_delete_layout'],
    'access arguments' => ['administer acb layout'],
    'type' => MENU_CALLBACK,
    'file' => 'src/Form/acb_delete_layout.php'
  ];
  
  $items['acb/acb_load_block_autocomplete_callback'] = [
    'page callback' => '\Drupal\\acb\\Helper\\AcbLoadBlock::get_blocks',
    'file' =>'src/Helper/AcbHelper.php',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  ];

  return $items;
}
/*
https://api.drupal.org/api/drupal/modules!block!block.api.php/function/hook_block_list_alter/7.x
*/


/**
 * Implements hook_admin_paths().
 */
function acb_admin_paths() {
  $paths = [
    'node/*/block_layout' => TRUE
  ];
  return $paths;
}


/**
 * Implements hook_page_alter().
 */
function acb_page_alter(&$page) {
  global $theme;
  $object = menu_get_object();
  
  if (isset($object->type) && isset($object->nid)) {
    $blocks_by_url = new AcbModelClass;
    $url_blocks = $blocks_by_url->load_by_url('node/'.$object->nid);
    
    if(is_object($url_blocks) && isset($url_blocks->data)) {
  
      $raw_blocks = unserialize($url_blocks->data);
  
      if (isset($raw_blocks[$theme])) {
        $blocks_pre_build = AcbHelper::clean_array($raw_blocks[$theme]);
        
        foreach ($blocks_pre_build as $region => $blocks) {
      		unset($page[$region]);
          $blocks = AcbHelper::get_renderized_block($blocks, $region, $theme);
          $order = AcbHelper::order_of_block($raw_blocks[$theme][$region]);
          $page[$region] = AcbHelper::clean_array(array_replace($order, $blocks));
      
        }
      }
    }
  }
  
}


